package com.salon.entity;

public enum CustomerNotificationType {
    BOOKING_CONFIRMED, BOOKING_CANCELLED, PAYMENT_SUCCESS, PAYMENT_REFUNDED,
    REVIEW_RESPONSE, COMMUNICATION_RECEIVED, LOYALTY_POINTS_EARNED,
    POLICY_UPDATED, PROMOTION_AVAILABLE, CONSULTATION_CONFIRMED,
    PAYMENT_REMINDER
}
