package com.salon.entity;

public enum NotificationType {
    NEW_BOOKING, COMPLAINT_FORWARDED, COMPLAINT_RECEIVED, PROFESSIONAL_PENDING,
    APPOINTMENT_CANCELLED, NEW_REVIEW, UNPAID_APPOINTMENT_ESCALATION
}
