package com.salon.entity;

public enum ProfessionalNotificationType {
    APPOINTMENT_CONFIRMED, APPOINTMENT_CANCELLED, NEW_REVIEW,
    COMPLAINT_RAISED, SUSPENSION_WARNING, SUSPENSION_NOTICE, REACTIVATED, POLICY_PUBLISHED
}
